version: "3.7"
services:
  redis:
    image: redis
    networks:
      test-tasks-network:
        ipv4_address: 172.20.2.10

  db:
    image: postgres
    networks:
      test-tasks-network:
        ipv4_address: 172.20.2.11
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: test_task_db
    volumes:
      - ../migrations:/docker-entrypoint-initdb.d

  api:
    build:
      context: ../
      dockerfile: ./test-tasks-docker/docker/api/Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    networks:
      test-tasks-network:
        ipv4_address: 172.20.2.12
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    volumes:
      - ../src:/app/src

networks:
  test-tasks-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.2.0/24